### ISSUE TITLE
Your Site not showing on site details till users are logged in? Do the following

### ISSUE THREAD

**Issue by mayeedwin** [neojato/DeLorean-v2#11]
## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

##Firebase Config

In your firebase console, go to database dashboard, click RULES, then make it this way;

{
  "rules": {
    ".read": "auth != false",
    ".write": "auth != false"
  }
}

You will be DONE!

Cheers!

**Comment by neojato** [comment]
Hi @mayeedwin, if you follow the [Site Setup](https://github.com/neojato/DeLorean-v2#managing-data) steps, you shouldn't have to do what you suggest when setting up your site. Please also make sure you are using the latest version of DeLorean-v2.
