### ISSUE TITLE
Optimise usage of async pipe

### ISSUE THREAD

**Issue by beeman** [neojato/DeLorean-v2#16]
## Expected Behavior

Ideally we should subscribe to observables as few times as possible.

## Current Behavior

Currently in a template a single observable is subscribed to various times.

## Possible Solution

Reduce usage of async by using this pattern:

```html
<div *ngIf="speaker$ | async as speakers ; else noSpeakers">
  Here are our {{ speakers | json }}, no need to subscribe in here :)
</div>

<ng-template #noSpeakers>
  I could not find any Speakers :(
</ng-template>
```

## Steps to Reproduce

1.
2.
3.
4.

## Possible Implementation

I was about to create a PR when I read the need for an issue, that's why I created this issue :-)

**Comment by neojato** [comment]
Thanks @beeman for the suggestion and the PR!
