### ISSUE TITLE
firebase-cloud-firestore

### ISSUE THREAD

**Issue by mayeedwin** [neojato/DeLorean-v2#20]
Awesome for progressive web apps and the offline feature just makes it super amazing!
[Checkout this codelab here ](https://pwafire.org/developer/codelabs/cloud-firestore-for-web/)

**Comment by neojato** [comment]
Firestore is awesome, but I think it's more worthwhile to focus efforts on refactoring to use the latest version of AngularFire2 instead. 

Open to seeing any efforts in refactoring DeLorean to utilize Firestore though. :)
