### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by MrCsabaToth** [neojato/DeLorean-v2#21]
`ng build` errors out

## Expected Behavior
after `npm install` `ng build` would succeed

## Current Behavior
`npm install`

```
...
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @agm/core@1.0.0-beta.3 requires a peer of @angular/common@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @agm/core@1.0.0-beta.3 requires a peer of @angular/core@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-bootstrap-md@4.3.7 requires a peer of chart.js@2.5.x but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1371 packages from 1226 contributors and audited 8203 packages in 22.855s
found 21 vulnerabilities (11 low, 4 moderate, 6 high)
  run `npm audit fix` to fix them, or `npm audit` for details

```

Then `ng build` fails with:

```
Your global Angular CLI version (6.1.1) is greater than your local
version (1.7.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
/home/csaba/repos/DeLorean-v2/node_modules/@angular/cli/ember-cli/lib/ui/index.js:56     
    this.outputStream.write(data);
                      ^

TypeError: Cannot read property 'write' of undefined
    at UI.write (/home/csaba/repos/DeLorean-v2/node_modules/@angular/cli/ember-cli/lib/ui/index.js:56:23)
    at UI.writeLine (/home/csaba/repos/DeLorean-v2/node_modules/@angular/cli/ember-cli/lib/ui/index.js:69:8)
    at callback (/home/csaba/repos/DeLorean-v2/node_modules/@angular/cli/tasks/build.js:44:29)
    at onCompiled (/home/csaba/repos/DeLorean-v2/node_modules/webpack/lib/Compiler.js:237:12)
    at applyPluginsAsync.err (/home/csaba/repos/DeLorean-v2/node_modules/webpack/lib/Compiler.js:510:14)
    at next (/home/csaba/repos/DeLorean-v2/node_modules/tapable/lib/Tapable.js:202:11)
    at Compiler.<anonymous> (/home/csaba/repos/DeLorean-v2/node_modules/webpack/lib/CachePlugin.js:78:5)
    at Compiler.applyPluginsAsyncSeries (/home/csaba/repos/DeLorean-v2/node_modules/tapable/lib/Tapable.js:206:13)
    at compilation.seal.err (/home/csaba/repos/DeLorean-v2/node_modules/webpack/lib/Compiler.js:507:11)
    at Compilation.applyPluginsAsyncSeries (/home/csaba/repos/DeLorean-v2/node_modules/tapable/lib/Tapable.js:195:46)
    at applyPluginsAsync.err (/home/csaba/repos/DeLorean-v2/node_modules/webpack/lib/Compilation.js:677:19)
    at next (/home/csaba/repos/DeLorean-v2/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.compilation.plugin (/home/csaba/repos/DeLorean-v2/node_modules/webpack/lib/ProgressPlugin.js:123:6)
    at Compilation.applyPluginsAsyncSeries (/home/csaba/repos/DeLorean-v2/node_modules/tapable/lib/Tapable.js:206:13)
    at applyPluginsAsync.err (/home/csaba/repos/DeLorean-v2/node_modules/webpack/lib/Compilation.js:668:11)
    at next (/home/csaba/repos/DeLorean-v2/node_modules/tapable/lib/Tapable.js:202:11)
```

## Steps to Reproduce
1. git clone repo
2. npm install
3. ng build

## Context (Environment)
Devuan ascii Linux distribution.

## Possible Implementation
Unfortunately I'm newbie with angular, ember, and several parts of this tech stack.

**Comment by neojato** [comment]
@MrCsabaToth Sorry to hear you are having troubles. Did you do a fresh clone? Asking b/c I know you've worked with DeLorean on a site before.

You might have to clear your `node_modules` folder and do a fresh `npm install`

Also, check that your `package.json` matches the one from this repository. I recently updated to use Angular CLI 6.1.1 and @angular/[packages] to 6.1.0. 

Based on the error message you posted, those are my only recommendations so far. Either doing a clean clone of the repo or clearing your `node_modules` directory.

Hope that helps!

**Comment by MrCsabaToth** [comment]
So my global and project package versions were different. After flushing the global as well (tried the clone from scratch multiple times) I got:

> 
> ERROR in Error: Metadata version mismatch for module /home/csaba/repos/DeLorean-v2/node_modules/@agm/core/index.d.ts, found version 4, expected 3, resolving symbol AppModule in /home/csaba/repos/DeLorean-v2/src/app/app.module.ts, resolving symbol AppModule in /home/csaba/repos/DeLorean-v2/src/app/app.module.ts, resolving symbol AppModule in /home/csaba/repos/DeLorean-v2/src/app/app.module.ts
>     at syntaxError (/home/csaba/repos/DeLorean-v2/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
>     at simplifyInContext (/home/csaba/repos/DeLorean-v2/node_modules/@angular/compiler/bundles/compiler.umd.js:24979:23)
>     at StaticReflector.simplify (/home/csaba/repos/DeLorean-v2/node_modules/@angular/compiler/bundles/compiler.umd.js:24991:13)
>     at StaticReflector.annotations (/home/csaba/repos/DeLorean-v2/node_modules/@angular/compiler/bundles/compiler.umd.js:24418:41)
>     at _getNgModuleMetadata (/home/csaba/repos/DeLorean-v2/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
>     at _extractLazyRoutesFromStaticModule (/home/csaba/repos/DeLorean-v2/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
>     at Object.listLazyRoutesOfModule (/home/csaba/repos/DeLorean-v2/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
>     at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/home/csaba/repos/DeLorean-v2/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
>     at AotPlugin._getLazyRoutesFromNgtools (/home/csaba/repos/DeLorean-v2/node_modules/@ngtools/webpack/src/plugin.js:240:66)
>     at _donePromise.Promise.resolve.then.then.then.then.then (/home/csaba/repos/DeLorean-v2/node_modules/@ngtools/webpack/src/plugin.js:493:24)
>     at <anonymous>

After some more fiddling it turns out that current `packages.json` installed `@agm/core@1.0.0-beta.3` which wanted angular v5 files as a peer dependency:

```
npm ERR! peer dep missing: @angular/common@^5.0.0 || ^6.0.0, required by @agm/core@1.0.0-beta.3
npm ERR! peer dep missing: @angular/core@^5.0.0 || ^6.0.0, required by @agm/core@1.0.0-beta.3
```

I needed to install exact version `@agm/core@1.0.0-beta.1` to make this go away, and now `ng build` and `ng serve` is successful.

**Comment by MrCsabaToth** [comment]
@neojato the recent updates brought up the package versions to current. After upgrading my global packages to that the build happens smoothly.
