### ISSUE TITLE
The Register/Buy Ticket button of the ticket cards doesn't work

### ISSUE THREAD

**Issue by MrCsabaToth** [neojato/DeLorean-v2#25]
The Register button of the ticket cards doesn't point to anywhere.

## Expected Behavior
Register button(s) should navigate to the same ticket URL as the menu or the "Reserve Your Seat", and theoretically that's the case looking at the DOM interpolation.

## Current Behavior
No href is interpolated despite the source code's intent.

## Possible Solution
Converting the `<button>` element into an `<a>`.

## Steps to Reproduce
1. On the home page scroll down to the ticket cards
2. Click on (any of) the Register button(s)

## Detailed Description
Could this be a result of moving from Angular v4 to v6?

## Possible Implementation
Replacing
`<button type="button" class="btn btn-primary waves-light" [href]="config?.ticketURL">Buy Ticket</button>`
with
`<a target="_blank" rel="noopener" [href]="config?.ticketURL" class="btn btn-primary waves-light" rel="nofollow">Buy Ticket</a>`

**Comment by MrCsabaToth** [comment]
PR #26

**Comment by neojato** [comment]
Great find! Thanks for the PR.
