### ISSUE TITLE
New projects and missing urls cause /null links

### ISSUE THREAD

**Issue by cjwhitsitt** [neojato/DeLorean-v2#32]
## Expected Behavior
When creating a new project that doesn't have webpages for tickets or sponsors, there shouldn't be broken links.

## Current Behavior
Currently, the ticket link is required but still read by two buttons on the home page (menu and hero). The sponsor button also continues to display even when the sponsor url is missing.

## Possible Solution
1. Hide the buttons if their url is missing regardless of if the url is required or not
2. Don't show some pages if urls are missing

**Comment by cjwhitsitt** [comment]
I'd prefer to just hide the buttons. Doing it this way also provides the site owner a way to disable the ticket or sponsor buttons after the event if they'd like.

**Comment by neojato** [comment]
Wasn't able to replicate on the sponsor button (already is being hidden), but disabled the Ticket button in hero until added in Site Config.
