### ISSUE TITLE
The map isn't shown 

### ISSUE THREAD

**Issue by MiaShopgal** [neojato/DeLorean-v2#36]
## Expected Behavior
After providing an map API key and set the address in the Venue Details. 
The map should be shown on the home page.

## Current Behavior
Showing venue but no map was shown.

## Possible Solution
I check the API key, it's valid to use. I change the address to a different one, but still, no map was shown.
Can't find any clue in the developer console.

## Steps to Reproduce
1. Set the mapsKey in firebase.config.ts
2. Set the address ( No. 50, Section 2, Heping East Road, Da’an District, Taipei City, Taiwan 106 ) in Venue Details
3. Visit website https://wtm-taipei-lighting-talk-0.firebaseapp.com/home
4. See no map.. :(

## Context (Environment)
Node.js v10.15.3

## Detailed Description
I think it's all listed above.

## Possible Implementation
I have no idea... :(

**Comment by neojato** [comment]
Hi @MiaShopgal, sorry I'm just seeing this. There might be an issue with how the Google Maps API turns the address string into map coordinates. Thanks for bringing to my attention, I'll do some digging and get back to you as soon as I can.

**Comment by MrCsabaToth** [comment]
It could be also if the GCP project which provided the Maps API key does not have payment method configured, then the map reverts to a version which displays a "developer" watermark and grayer area. I can imagine if some throttle limits are reached it may error out?

**Comment by MiaShopgal** [comment]
@neojato Thanks for your feedback. I really appreciate your time. Let me know if you need more info.
@MrCsabaToth I believe the GCP project is set up with a valid payment method account. I don't see any sight of Map. I know this watermark you mention. I saw it before
![image](https://user-images.githubusercontent.com/2044967/62009031-d9418b80-b18c-11e9-9a6c-e3e962d9a16a.png)
. 

In my case, there's no map at all :(

https://wtm-taipei-lighting-talk-0.firebaseapp.com/home

**Comment by MrCsabaToth** [comment]
Looking in Chrome Incognito mode, there's a JS error:

> content_script_bundle.js:16 Uncaught TypeError: c.querySelectorAll is not a function
>     at MutationObserver.<anonymous> (content_script_bundle.js:16)

Since it's a minimized bundle, can you look up where's this coming from in your dev version?

**Comment by MiaShopgal** [comment]
@MrCsabaToth Fist of all, thank you for spending time on this! 

> Looking in Chrome Incognito mode, there's a JS error:

Can you show me how to find this JS error?
The only error I saw is this:
![image](https://user-images.githubusercontent.com/2044967/62137944-60bc0580-b319-11e9-839e-0e67874ddecd.png)

> 
> > content_script_bundle.js:16 Uncaught TypeError: c.querySelectorAll is not a function
> > at MutationObserver. (content_script_bundle.js:16)
> 
> Since it's a minimized bundle, can you look up where's this coming from in your dev version?

I try to search "querySelectorAll" and "MutationObserver".
There's 100+ result in my source code.
no result for "content_script_bundle"
I wish I know much more about js... :(

**Comment by neojato** [comment]
Hi @MiaShopgal, I looked through your repo and the branch you created. I noticed some code that doesn't look like it's been deployed. Does your local code match what is in that branch?

Aside from that, looking into things a bit it looks like I initially expected. The Google Maps API seems to have not correctly saved the geolocation for the address of the venue when you entered it into the config.

I copy/pasted the address from your post and checked against the Google Maps API and got the lat/long for the venue that should have been saved:
- lat: 25.0254015
- long: 121.5383179

Try to copy the address from here and paste in the admin config and let us know.

**Comment by MrCsabaToth** [comment]
> Can you show me how to find this JS error?
> The only error I saw is this:
> ![image](https://user-images.githubusercontent.com/2044967/62137944-60bc0580-b319-11e9-839e-0e67874ddecd.png)

I have to apologize, some plugins in my browser caused the error I saw. After disabling all plugins, I saw the error about the Google Tag Manager (GTM-XXXXXXX). JS errors can stop the execution chain, so first eliminate that. Right now it's listed as an optional step in the docs, but just go ahead and configure it: https://github.com/neojato/DeLorean-v2#google-tag-manager-setup-optional

**Comment by MrCsabaToth** [comment]
Actually, looks like my DevFest site is missing the map as well. I need to debug that this week.

**Comment by MrCsabaToth** [comment]
Ok, so the map only shows if the siteConfig.venueGeoData is populated. That should populate when you specify the venue street address, then your browser's JS code would call for a Geocoding service which derives the Lat/Lon coordinates from the street address (https://github.com/neojato/DeLorean-v2/blob/8fa4417d5e3b6382557b7adc4e0814281382ea4c/src/app/admin/site-config/site-config.component.ts#L51).

What I see in the browser when I specify a venue street address on the site config page: `geocodingAPIService Other error REQUEST_DENIED`. I'll debug that later further. I suspect we may miss some API privileges BTW. We should add that to the install doc once figured out.

The good news is that there's a workaround: until this is fixed, you can open the Firebase project, navigate into the database and add the required lat/lon there.

**Comment by MrCsabaToth** [comment]
Still for the workaround, when you fill in the lat/lng manually, here is the shape of data what you need:
![Screenshot_2019-08-10_19-31-46](https://user-images.githubusercontent.com/744949/62828879-dcce0d00-bba5-11e9-809d-6f2c1e7cd5bc.png)

**Comment by MrCsabaToth** [comment]
On the actual `REQUEST_DENIED` errorof the geocoding request, the detailed message is `"This API project is not authorized to use this API."`. So it's what I suspected, we need to enable some additional API besides Maps.

**Comment by MrCsabaToth** [comment]
So what have happened is that most probably several years ago when this project started the Maps API Enable also involved the Geocoding calls. Today the family of Maps APIs contains more than a dozen APIs, like Places, Street View, and so on, and now Geocoding is separate from the generic Maps (display) JavaScript API. Which is a good thing because you can control things fin grained. So I needed to enable the Geocoding API:

![Screenshot_2019-08-10_19-53-23](https://user-images.githubusercontent.com/744949/62829032-44d22280-bba9-11e9-9785-815b661e8747.png)

![Screenshot_2019-08-10_19-54-51](https://user-images.githubusercontent.com/744949/62829033-47cd1300-bba9-11e9-95d8-fa49e712baed.png)

Now when I change the venue address, the lat/lng is successfully populated in the DB. We'll need to update the docs.

**Comment by MrCsabaToth** [comment]
@MiaShopgal let me know if this helped for you.

**Comment by MiaShopgal** [comment]
> @MiaShopgal let me know if this helped for you.

Yes, indeed!
I got the map shown on my site now!!
Thank you so much!!

**Comment by neojato** [comment]
It does seem that the Geocoding API changed from an "always on" to having to enable. Thanks for the find @MrCsabaToth.

Glad your map shows now @MiaShopgal!
