### ISSUE TITLE
Dependencies broken

### ISSUE THREAD

**Issue by benju69** [neojato/DeLorean-v2#43]
**Describe the bug**
I wanted to try Delorean

I got this error when I do npm install 

npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: delorean@0.0.0
npm ERR! Found: @angular/common@6.1.10
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^6.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^4.0.0" from angularfire2@5.0.0-rc.3
npm ERR! node_modules/angularfire2
npm ERR!   angularfire2@"5.0.0-rc.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

More errors when I update/change these deps

**Expected behavior**
Should work

**Comment by neojato** [comment]
@benju69 - we've updated the project to Angular 9 and cleaned up the npm dependencies. Please try again and if you're still experiencing issues feel free to create a new bug.
