### ISSUE TITLE
Upgrade to latest Angular

### ISSUE THREAD

**Issue by MrCsabaToth** [neojato/DeLorean-v2#44]
**Is your feature request related to a problem? Please describe.**
Currently the app is Angular 6.1 based. Before tackling any feature requests (although merging my outstanding PR) we should upgrade to latest Angular.

**Describe the solution you considered**
I was looking at https://update.angular.io/?l=2&v=6.1-15.0
I'd follow the link bellow and perform the 9 major upgrades step-by-step

**Comment by andmenegaz** [comment]
Hey guys, this is a fork of a forked project, but I've upgraded it to Angular 9.
https://github.com/andmenegaz/devfestsul2022

**Comment by neojato** [comment]
Accepted PR #45 to move this project onto Angular 9. 

@MrCsabaToth do you mind updating PR #31 to sort out the merge conflicts? Thanks in advance!

**Comment by MrCsabaToth** [comment]
> Accepted PR #45 to move this project onto Angular 9.
> 
> @MrCsabaToth do you mind updating PR #31 to sort out the merge conflicts? Thanks in advance!

I definitely should. I'll message here if when I get to it (no ETA).
