### ISSUE TITLE
Social links are for GDG, not DevFest

### ISSUE THREAD

**Issue by cjwhitsitt** [neojato/DeLorean-v2#5]
The social icons at the bottom of the page link to GDG pages, not DevFest pages. Since this is the DevFest site, I'd prefer they link to DevFest resources. 

I see a couple options:
1. Maybe make it configurable which ones go there
2. Move the GDG ones to an "Learn more about GDG {chapter} [F] [T] [M] [G] ..." and make the existing ones DevFest

**Comment by mayeedwin** [comment]
A good idea but maybe the Meet up and website links should remain GDG and the disclaimer

**Comment by neojato** [comment]
fixed with 1a854b8, 05126cb, & 613a9a3
