### ISSUE TITLE
Call For Papers/Call for sponsors is null

### ISSUE THREAD

**Issue by christurvey** [neojato/DeLorean-v2#6]
When creating an event there is a time for call for papers and there is a time for call for sponsors. By the time I set up the project for the website for the event those two dates have passed. I don't really need links explaining to people that the time has passed. 
## Expected Behavior

I would love a null field in the CFP or CFS to hide the buttons that take me to those actions.
## Current Behavior

Currently we have buttons that show and then they link off to null
## Possible Solution

In my local version I went through and added a few NgIf's to the links. But this should be part of the main project.
## Steps to Reproduce

1. Just leave an empty link on the call for papers or Become a Sponsor

## Possible Implementation

In addition to adding the NgIf statements, it might also be awesome if we had a date field call it "endOfCallForPapersDate" in which the button would hide after that date and the same things but for sponsor requests.

**Comment by christurvey** [comment]
Same hidden if null on title and company on the speaker profile page. Want me to create another Issue or just note it here?

**Comment by neojato** [comment]
Thanks for the suggestions @christurvey! Instead of a date field on when to enable/expire the links, what are your thoughts on a simple checkbox that when checked turns on the link and unchecked disables the link (if filled in)?

**Comment by christurvey** [comment]
Filling in a date field that expires would allow a date to be set without the organizer having to remember to go in and close it off. I would hope for a datepicker... but a checkbox to hide it would at least offer the ability to hide the links. However if we just implemented the hide if empty then we wouldn't have to do really much of anything... just delete the URL for our Call For Papers/Call for Sponsors.
If removing the URL's from the page requires user interaction to remove them... just deleting the URL from the config could be adequate. No new database field!

**Comment by neojato** [comment]
Will proceed with the empty URL option in the short term. Thanks for the feedback!

**Comment by neojato** [comment]
fixed with 4b113ef5dcaa68a930a4be843ca10fc36d687f54, efe3a3e2cd52cd64c8ba48fe9b8d06195b1fe968, fdd13e208139e9db48d69af98f9d5b21c34a2092, a006854db37a6ddea427c0bfd16fca5dc00089ad, & 8036a1cb2ed0814a0caf3e85565bdb3bc2a0fe97
